FROM golang:1.13 as builder
WORKDIR /{{.Entrypoint}}

# Retrieve application dependencies using go modules.
# Allows container builds to reuse downloaded dependencies.
COPY go.* ./
RUN go mod download

# Copy local code to the container image.
COPY . ./

# Build the binary.
# -mod=readonly ensures immutable go.mod and go.sum in container builds.
RUN CGO_ENABLED=0 go build -mod=readonly -o runtime ./cmd/{{.Entrypoint}}

# Use the official Alpine image for a lean production container.
# https://hub.docker.com/_/alpine
# https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
FROM alpine:3
RUN apk add --no-cache ca-certificates

# Copy the binary to the production image from the builder stage.
COPY --from=builder /{{.Entrypoint}}/runtime /{{.Entrypoint}}

# Run the web service on container startup.
ENTRYPOINT ["/{{.Entrypoint}}"]